Algoritmo "aula 7"

Var
nome : caractere
produtos : vetor[1..4] de caractere
numeros : vetor [1..3] de inteiro
i : inteiro

Inicio
nome <- "victor"
nome <- "alessandro"

produtos[1] <- "banana"
produtos[2] <- "salgadinho"
produtos[3] <- "refrigerante"
produtos[4] <- "cafe"



//ENQUANTO (CONDICAO)
//CONTADOR <- CONTADOR + 1

para i <- 1 ate 3 faca
leia(numeros[i])
fimPara

para i <- 1 ate 3 faca
  escreval("n",i,"º",numeros[i])
fimPara
Fimalgoritmo