Algoritmo "semnome"

Var
senha, senhaCorreta : caractere
usuario , usuarioCorreto : caractere
Inicio
usuarioCorreto <- "gabilima"
senhaCorreta <- "gabii"

escreval("qual é o usuario")
leia (usuario)
escreval("qual  é a senha")
leia (senha)

se (usuario=usuarioCorreto)entao
   escreval("usuário correto")
senao
     escreval("usuário icorreto")
fimSe

se (senha =senhaCorreta)entao
   escreval("senha correta")
senao
     escreval("senha incorreta!")
fimSe


Fimalgoritmo